# Generated by Django 5.2.3 on 2025-07-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('bakery', 'Bakery'), ('mess_breakfast', 'Mess - Breakfast'), ('mess_lunch', 'Mess - Lunch'), ('mess_dinner', 'Mess - Dinner'), ('canteen_breakfast', 'Canteen - Breakfast'), ('canteen_lunch', 'Canteen - Lunch'), ('canteen_dinner', 'Canteen - Dinner')], max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
            ],
        ),
    ]
