# Generated by Django 5.2.3 on 2025-07-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=25)),
                ('Lastname', models.CharField(max_length=25)),
                ('Phone', models.IntegerField(null=True)),
                ('join_date', models.DateField(null=True)),
            ],
        ),
    ]
