# Generated by Django 5.2.3 on 2025-07-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Id',
            field=models.IntegerField(verbose_name=int),
        ),
        migrations.AlterField(
            model_name='member',
            name='Phone',
            field=models.IntegerField(verbose_name=int),
        ),
    ]
